### ISSUE TITLE
ISSUE: Seems to be broken for Google Play Music with today's new UI release

### ISSUE THREAD

**Issue by izekil** [mindfreakthemon/chime#2]
Same issue in other gmusic scrobblers. Needless to say about "Lyrics" feature...
I like the redesign btw :)

Well, the trаck titlе is nоw in div#player-song-title.
And it looks like play/pause buttоn еlеmеnt has changed from button to sg-icоn-buttоn resulting in #player sj-icon-button[data-id="play-pause"].

At first (and pretty newbie) glance the other selectors in googlemusic.js and v2/googlemusic.js seem to still be okay, but I'm rlyy not sure what else should be checked.
Hope it help a little.
Thanks!

**Comment by mindfreakthemon** [comment]
Material design finally came to google music.
Looks cool. A bit uncomfortable at first, though.

I will try to figure out where to place Lyrics and fix other selectors ASAP.

Thank you for your input!
